version: '3.1'
services:
  sharedpsql:
    image: postgres:12
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jis6
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: testdb
    volumes:
      - ./data12:/var/lib/postgresql/data

#  web:
#    image: tomcat:10.0.10-jdk11-openjdk-slim-buster
#    ports:
#      - "8000:8080"
#    depends_on:
#      - "sharedpsql"
#    volumes:
#      - ./petclinic.war:/usr/local/tomcat/webapps/petclinic.war


